# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-19 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191219_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreContainProduct',
            new_name='Contain',
        ),
    ]
