# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-20 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191220_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contain',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='idProduct',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='infourl',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='thumburl',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='title',
        ),
    ]
