# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-08 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191220_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='distance',
            field=models.IntegerField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='store',
            name='url',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
