import models.product
p = Product(idProduct = 1, title = 'cafe', name = 'Vinacafe', author='VINACAFE', rating=4, quantity=41, price=45000, thumburl='https://vinacafebienhoa-cms-production.s3-ap-southeast-1.amazonaws.com/iblock/b56/b56fb678d8abcbd85957eb7b27f2e587.png', infourl='https://www.kiotviet.vn/')
p.save()
p = Product(idProduct = 2, title = 'cozz', name = 'COZZ CANDY', author='DHG PHARMA', rating=3, quantity=10, price=10000, thumburl='http://www.dhgpharma.com.vn/images/stories/virtuemart/product/cozz%20Hop%2012.png', infourl='https://www.kiotviet.vn/')
p.save()
p = Product(idProduct = 3, title = 'lipton', name = 'Trà  lipton', author='Unilever', rating=2, quantity=10, price=40000, thumburl='http://htmart.org/wp-content/uploads/2018/11/18-2.jpg', infourl='https://www.kiotviet.vn/')
p.save()
p = Product(idProduct = 4, title = 'afc', name = 'Bánh AFC Lúa Mì', author='Kinh Đô', rating=5, quantity=15, price=25000, thumburl='https://cdn.tgdd.vn/Products/Images/3357/79550/bhx/banh-dd-afc-lua-mi-hop-200g-2-org.jpg', infourl='https://www.kiotviet.vn/')
p.save()
p = Product(idProduct = 5, title = 'lavie', name = 'Nước đóng chai lavie 350ml', author='Nestle', rating=4, quantity=22, price=5000, thumburl='https://www.nuocsuoi.vn/wp-content/uploads/2018/08/nuoc-khoang-lavie-350ml-0304.jpg', infourl='https://www.kiotviet.vn/')
p.save()
